// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_universal.FL_DataBase_DataReciever.Head_Count_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_universal.FL_ControlId_Dynamic.Get_Ids_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String,System.String)~System.String[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_universal.FL_ControlId_Dynamic.Head_Count_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0060:Remove unused parameter", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_DataBase.FL_MySql.FL_MySqlExecutor.ExecuteMySqlCommand(MySql.Data.MySqlClient.MySqlConnection,MySql.Data.MySqlClient.MySqlCommand,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_DataBase.FL_MySql.FL_MySqlExecutor.ExecuteMySqlCommand(MySql.Data.MySqlClient.MySqlConnection,MySql.Data.MySqlClient.MySqlCommand,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_Controls.FL_ControlId_Dynamic.Head_Count_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String,System.String)~System.Int32")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_Controls.FL_ControlId_Dynamic.Get_Ids_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String,System.String)~System.String[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0059:Unnecessary assignment of a value", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_Controls.FL_ControlId_Dynamic.Get_Ids_DB(MySql.Data.MySqlClient.MySqlCommand,MySql.Data.MySqlClient.MySqlConnection,System.String,System.String,System.String)~System.String[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_webpage.FL_DataBase.FL_MySql.FL_MySqlExecutor.FL_Check_Column_Exists(MySql.Data.MySqlClient.MySqlConnection,MySql.Data.MySqlClient.MySqlCommand,System.String,System.String,System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Dbf_Helper.FL_DbfData_To_Excel.DataSetToExcel_single_excel_file(System.Data.DataSet)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Dbf_Helper.FL_DbfData_To_Excel.DataToExcel_single_excel_file(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Dbf_Helper.FL_DbfData_To_Excel.DataSetToExcel_single_excel_file(System.Data.DataSet)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Dbf_Helper.FL_DbfData_To_Excel.DataToExcel_single_excel_file(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1814:Prefer jagged arrays over multidimensional", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Excel_Data_Interop.FL_DataTableToExcel_Helper.FL_DataTableToExcel(System.Data.DataTable,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Excel_Data_Interop.FL_DataTableToExcel_Helper.FL_DataTableToExcel(System.Data.DataTable,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification = "<Pending>", Scope = "member", Target = "~M:frontlook_dotnetframework_library.FL_desktopapp.FL_Excel_Data_Interop.FL_DataTableToExcel_Helper.DataTableToExcel_Excel_Visible(System.Data.DataTable,System.String)")]
